export const mockTripsData = (twoDaysAgo: Date, yesterday: Date, tomorrow: Date, nextWeekStart: Date, nextWeekEnd: Date) => [
    {
        id: 'mock-active',
        carName: 'Porsche 911',
        model: 'Carrera S',
        year: '2022',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
        startDate: twoDaysAgo.toISOString(),
        endDate: tomorrow.toISOString(),
        dbStatus: 'APPROVED',
        location: 'Av. Paulista, São Paulo',
        owner: 'Roberto S.',
        avatarUrl: 'https://i.pravatar.cc/150?u=roberto',
        price: 2450,
    },
    {
        id: 'mock-pending',
        carName: 'BMW X6',
        model: 'M Competition',
        year: '2021',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980adade?auto=format&fit=crop&w=1200&q=80',
        startDate: nextWeekStart.toISOString(),
        endDate: nextWeekEnd.toISOString(),
        dbStatus: 'PENDING',
        location: 'Aeroporto de Congonhas',
        owner: 'Carla M.',
        avatarUrl: 'https://i.pravatar.cc/150?u=carla',
        price: 1800,
    },
    {
        id: 'mock-confirmed',
        carName: 'Mercedes C300',
        model: 'Cabriolet',
        year: '2020',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
        startDate: nextWeekStart.toISOString(),
        endDate: nextWeekEnd.toISOString(),
        dbStatus: 'APPROVED',
        location: 'Vila Madalena, SP',
        owner: 'André L.',
        avatarUrl: 'https://i.pravatar.cc/150?u=andre',
        price: 1200,
    },
    {
        id: 'mock-rejected',
        carName: 'Audi RS6',
        model: 'Avant',
        year: '2023',
        imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
        startDate: nextWeekStart.toISOString(),
        endDate: nextWeekEnd.toISOString(),
        dbStatus: 'REJECTED',
        location: 'Barra da Tijuca, RJ',
        owner: 'Marcos P.',
        avatarUrl: 'https://i.pravatar.cc/150?u=marcos',
        price: 3200,
    },
    {
        id: 'mock-completed',
        carName: 'Volvo XC90',
        model: 'Hybrid',
        year: '2021',
        imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80',
        startDate: twoDaysAgo.toISOString(),
        endDate: yesterday.toISOString(),
        dbStatus: 'APPROVED',
        location: 'Curitiba, PR',
        owner: 'Ana B.',
        avatarUrl: 'https://i.pravatar.cc/150?u=ana',
        price: 950,
    },
    {
        id: 'mock-cancelled',
        carName: 'Lexus RX',
        model: '450h+',
        year: '2023',
        imageUrl: 'https://images.unsplash.com/photo-1627446558085-e6f77ec62f98?auto=format&fit=crop&w=1200&q=80',
        startDate: nextWeekStart.toISOString(),
        endDate: nextWeekEnd.toISOString(),
        dbStatus: 'CANCELLED',
        location: 'Campinas, SP',
        owner: 'Fernando T.',
        avatarUrl: 'https://i.pravatar.cc/150?u=fernando',
        price: 2100,
    },
    {
        id: 'mock-expired',
        carName: 'Land Rover',
        model: 'Defender 110',
        year: '2022',
        imageUrl: 'https://images.unsplash.com/photo-1605895311904-8785055b80ee?auto=format&fit=crop&w=1200&q=80',
        startDate: twoDaysAgo.toISOString(),
        endDate: yesterday.toISOString(),
        dbStatus: 'PENDING',
        location: 'Belo Horizonte, MG',
        owner: 'Julia R.',
        avatarUrl: 'https://i.pravatar.cc/150?u=julia',
        price: 2800,
    }
];
